spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sis
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    jwt:
      token:
        security.jwt.token.secret-key: my-secret-key
        access-token-expiration: 900000   # 15 минут
        refresh-token-expiration: 86400000 # 24 часа