security.jwt.token.secret-key: my-secret-key

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sis
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect